In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import plotly.graph_objs as go

Yahoo Finance API will need 3 mandatory arguments in this order:

- Tickers (1)
- Start date + End date or Period (2)
- Interval (3)

### example: yf.download(tickers="arg1",period="arg2",interval="arg3")

In [3]:
# The interval is 5 min
data = yf.download(tickers='UBER', period='5d', interval='5m')
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2021-05-14 09:30:00-04:00,45.029999,45.330002,44.849998,45.099998,45.099998,935545
2021-05-14 09:35:00-04:00,45.110001,45.209999,44.900002,45.189999,45.189999,408626
2021-05-14 09:40:00-04:00,45.200001,45.355202,44.915001,45.290001,45.290001,595004
2021-05-14 09:45:00-04:00,45.299999,45.310001,45.080002,45.139999,45.139999,358727
2021-05-14 09:50:00-04:00,45.139999,45.509998,45.084999,45.395000,45.395000,515469
...,...,...,...,...,...,...
2021-05-20 14:45:00-04:00,49.419998,49.424999,49.360001,49.417500,49.417500,75602
2021-05-20 14:50:00-04:00,49.415001,49.505001,49.349998,49.500000,49.500000,129447
2021-05-20 14:55:00-04:00,49.500000,49.547699,49.465000,49.483501,49.483501,222228
2021-05-20 15:00:00-04:00,49.480000,49.480000,49.360001,49.430000,49.430000,27556
2021-05-20 15:01:41-04:00,49.445000,49.445000,49.445000,49.445000,49.445000,0